export const ADD_POST = "ADD_POST";
export const REMOVE_POST = "REMOVE_POST";
export const EDIT_POST = "EDIT_POST";

export const FETCH_ALL_POSTS = "FETCH_ALL_POSTS";
export const FETCH_ALL_POSTS_FAILURE = "FETCH_ALL_POSTS_FAILURE";

export const FETCH_USERDATA = "FETCH_USERDATA";
export const FETCH_USERDATA_FAILURE = "FETCH_USERDATA_FAILURE";

export const FETCH_COMMENTS = "FETCH_COMMENTS";
export const FETCH_COMMENTS_FAILURE = "FETCH_COMMENTS_FAILURE";
